#!/usr/bin/env python3
from __future__ import annotations

import ipaddress
import sqlite3
from pathlib import Path


PROJECT_ROOT = Path("/home/admin/ai-tool")
DB_PATH = PROJECT_ROOT / "data" / "snapshots.db"
OUTPUT_PATH = Path("/etc/nginx/snippets/ai-tool-ip-blocklist.conf")


def is_safe_to_block(ip: str) -> bool:
    ip = str(ip or "").strip()

    if not ip:
        return False

    try:
        obj = ipaddress.ip_address(ip)
    except Exception:
        return False

    # 不封本机、内网、链路本地、保留地址
    if obj.is_loopback or obj.is_private or obj.is_link_local or obj.is_reserved:
        return False

    return True


def main() -> None:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS v155_security_ip_blocklist (
            ip TEXT PRIMARY KEY,
            reason TEXT,
            source TEXT,
            is_active INTEGER DEFAULT 1,
            created_at TEXT,
            updated_at TEXT
        )
        """
    )

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS v155_security_ip_whitelist (
            ip TEXT PRIMARY KEY,
            note TEXT,
            created_at TEXT
        )
        """
    )

    whitelist = {
        row["ip"]
        for row in conn.execute(
            "SELECT ip FROM v155_security_ip_whitelist"
        ).fetchall()
    }

    rows = conn.execute(
        """
        SELECT ip, reason, updated_at
        FROM v155_security_ip_blocklist
        WHERE is_active=1
        ORDER BY updated_at DESC
        """
    ).fetchall()

    conn.close()

    deny_lines = []

    for row in rows:
        ip = str(row["ip"] or "").strip()

        if ip in whitelist:
            continue

        if not is_safe_to_block(ip):
            continue

        reason = str(row["reason"] or "").replace("\n", " ")[:120]
        updated_at = str(row["updated_at"] or "")

        deny_lines.append(
            f"deny {ip};  # {updated_at} {reason}"
        )

    content = [
        "# Auto generated by /home/admin/ai-tool/scripts/sync_nginx_blocklist.py",
        "# Do not edit manually.",
        "",
    ]

    if deny_lines:
        content.extend(deny_lines)
    else:
        content.append("# No active blocked IP.")

    content.extend(
        [
            "",
            "allow all;",
            "",
        ]
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(content), encoding="utf-8")

    print(f"synced {len(deny_lines)} blocked IP(s) to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
